config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :foods
  resources :food_groups
  resources :components
  resources :traits
  devise_for :users
  root 'home#index'
end

app/models/trait.rb
# frozen_string_literal: true

class Trait < ApplicationRecord
  include Blamable

  enum kind: { positive: 0, negative: 1 }

  validates :kind, presence: true, inclusion: { in: kinds.keys }
  validates :title, presence: true, length: { in: 5..100 }, uniqueness: true
end

app/controllers/traits_controller.rb
# frozen_string_literal: true

class TraitsController < ApplicationController
  before_action :set_trait, only: %i[create show edit update destroy]
  before_action :set_breadcrumbs

  def index
    @q = Trait.ransack(params[:q])
    @traits = @q.result(distinct: true).includes(:created_by, :updated_by).order(created_at: :desc)

    respond_with(@traits) do |format|
      format.html { @traits = @traits.page(@page).per(@per_page) }
      format.csv { render body: Trait.to_csv(@traits, %i[kind title created_by_email created_at]) }
    end
  end

  def show
    respond_with(@trait)
  end

  def new
    @trait = Trait.new
    respond_with(@trait)
  end

  def edit; end

  def create
    @trait.save
    respond_with(@trait)
  end

  def update
    @trait.update(trait_params)
    respond_with(@trait)
  end

  def destroy
    @trait.destroy
    respond_with(@trait)
  end

  private

  def set_breadcrumbs
    set_breadcrumbs_for(Trait, @trait)
  end

  def set_trait
    @trait = params.key?(:id) ? Trait.find(params[:id]) : Trait.new(trait_params)
  end

  def trait_params
    params.require(:trait).permit(:title, :kind)
  end
end

app/views/traits/_filter.html.slim
#search
  .card.rounded
    #headingOne.card-header.rounded-top[role="tab"]
      a.collapsed[data-toggle="collapse" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne"]
        i.icons.icon-magnifier
        =< t('actions.filter')
      .card-header-actions
        a.card-header-action.btn-minimize[href="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true"]
          i.icon-arrow-up
    #collapseOne.collapse[role="tabpanel" aria-labelledby="headingOne" data-parent="#search" style=""]
      = search_form_for @q do |f|
        .card-body
          .row
            .form-group.col-sm-3
              = f.label :kind_eq
              = f.select :kind_eq, Trait.human_enum_values_to_a(:kind), { include_blank: true }, class: 'form-control'
            .form-group.col-sm-3
              = f.label :title_cont
              = f.search_field :title_cont, class: 'form-control'
        .card-footer.rounded-bottom.text-right
          = f.submit t('actions.filter'), class: 'btn btn-primary rounded'

app/views/traits/_form.html.slim
.row.justify-content-md-center
  .card.rounded.w-75
    .card-header.rounded-top
      i.icon-note
      =< t("actions.#{@trait.persisted? ? 'edit' : 'new'}", name: Trait.model_name.human)

    = simple_form_for @trait do |f|
      .card-body
        = f.error_notification
        = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

        .form-inputs
          = f.input :kind, collection: Trait.human_enum_values_to_h(:kind), label_method: :second, value_method: :first
          = f.input :title

      .card-footer.rounded-bottom.text-right
        =< link_to t('actions.back'), traits_path, class: 'btn btn-secondary rounded'
        = f.button :submit, class: 'btn btn-primary rounded ml-2' do
          i.fa.fa-pencil.fa-lg

app/views/traits/index.html.slim
== render 'filter'

.card.rounded.card-accent-primary
  .card-header.rounded-top
    i.icons.icon-list
    =< Trait.model_name.human.pluralize
    .card-header-actions
      = link_to new_trait_path, class: 'card-header-action' do
        i.icon-note
  .card-body
    table.table.table-responsive-sm.table-striped
      thead
        tr
          th = Trait.human_attribute_name :kind
          th = Trait.human_attribute_name :title
          th = Trait.human_attribute_name :created_at
          th = Trait.human_attribute_name :created_by
          th.w-150px
      tbody
        - @traits.each do |trait|
          tr
            td
              span.badge.rounded class="badge-#{ trait.positive? ? 'success' : 'danger' }"
                = trait.human_enum_value :kind
            td = trait.title
            td = trait.created_at.to_formatted_s :short
            td = trait.created_by.email
            td
              = link_to trait_path(trait), class: 'btn btn-link', data: { toggle: :tooltip, placement: :top}, title: t('actions.show', name: '') do
                i.icon-eye
              = link_to edit_trait_path(trait), class: 'btn btn-link', data: { toggle: :tooltip, placement: :top}, title: t('actions.edit', name: '') do
                i.icon-note
              =< link_to trait, data: { confirm: t('alerts.are_you_sure'), toggle: :tooltip, placement: :top }, method: :delete, class: 'btn btn-link', title: t('actions.destroy', name: '') do
                i.icon-close.text-danger
    .d-flex.float-right
      .mr-3.pt-2
        = page_entries_info @traits
      => paginate @traits
      - unless @traits.empty?
        = link_to traits_path(format: :csv, params: request.query_parameters), class: 'btn btn-primary rounded h-35px ml-2' do
          i.icon-cloud-download

app/views/traits/show.html.slim
.row.justify-content-md-center
  .col-7
    ul.list-group.rounded-top
      li.list-group-item.rounded-top.active
        h4.pull-left.m-0
          = Trait.model_name.human
          small  ##{ @trait.id }
        = link_to edit_trait_path(@trait), class: 'text-white pull-right', data: { toggle: :tooltip, placement: :top}, title: t('actions.edit', name: '') do
          i.icon-note
      li.list-group-item
        h6.w-100px.d-inline-flex.font-weight-bold.text-uppercase.text-right.text-monospace
          = Trait.human_attribute_name :kind
        span.float-right
          = @trait.human_enum_value :kind
      li.list-group-item
        h6.w-100px.d-inline-flex.font-weight-bold.text-uppercase.text-right.text-monospace
          = Trait.human_attribute_name :title
        span.float-right
          = @trait.human_enum_value :title

    = link_to t('actions.back'), traits_path, class: 'btn btn-secondary rounded mt-3 float-right'