config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :foods
  resources :food_groups
  resources :components
  resources :traits
  devise_for :users
  root 'home#index'
end

app/models/food_group.rb
# frozen_string_literal: true

class FoodGroup < ApplicationRecord
  include Blamable

  validates :name, presence: true, length: { in: 5..100 }, uniqueness: { case_sensitive: false }
  validates :description, length: { maximum: 500 }
end

app/controllers/food_groups_controller.rb
# frozen_string_literal: true

class FoodGroupsController < ApplicationController
  before_action :set_food_group, only: %i[create show edit update destroy]
  before_action :set_breadcrumbs

  def index
    @q = FoodGroup.ransack(params[:q])
    @food_groups = @q.result(distinct: true).includes(:created_by, :updated_by).order(created_at: :desc)

    respond_with(@food_groups) do |format|
      format.html { @food_groups = @food_groups.page(@page).per(@per_page) }
      format.csv { render body: FoodGroup.to_csv(@food_groups, %i[name description created_by_email created_at]) }
    end
  end

  def show
    respond_with(@food_group)
  end

  def new
    @food_group = FoodGroup.new
    respond_with(@food_group)
  end

  def edit; end

  def create
    @food_group.save
    respond_with(@food_group)
  end

  def update
    @food_group.update(food_group_params)
    respond_with(@food_group)
  end

  def destroy
    @food_group.destroy
    respond_with(@food_group)
  end

  private

  def set_breadcrumbs
    set_breadcrumbs_for(FoodGroup, @food_group)
  end

  def set_food_group
    @food_group = params.key?(:id) ? FoodGroup.find(params[:id]) : FoodGroup.new(food_group_params)
  end

  def food_group_params
    params.require(:food_group).permit(:name, :description)
  end
end

app/views/food_groups/_form.html.slim
.row.justify-content-md-center
  .card.rounded.w-75
    .card-header.rounded-top
      i.icon-note
      =< t("actions.#{@food_group.persisted? ? 'edit' : 'new'}", name: FoodGroup.model_name.human)

    = simple_form_for @food_group do |f|
      .card-body
        = f.error_notification
        = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

        .form-inputs
          = f.input :name
          = f.input :description

      .card-footer.rounded-bottom.text-right
        =< link_to t('actions.back'), food_groups_path, class: 'btn btn-secondary rounded'
        = f.button :submit, class: 'btn btn-primary rounded ml-2' do
          i.fa.fa-pencil.fa-lg

app/views/food_groups/index.html.slim
== render 'filter'

.card.rounded.card-accent-primary
  .card-header.rounded-top
    i.icons.icon-list
    =< FoodGroup.model_name.human.pluralize
    .card-header-actions
      = link_to new_food_group_path, class: 'card-header-action' do
        i.icon-note
  .card-body
    table.table.table-responsive-sm.table-striped
      thead
        tr
          th = FoodGroup.human_attribute_name :name
          th = FoodGroup.human_attribute_name :description
          th.w-150px
      tbody
        - @food_groups.each do |food_group|
          tr
            td = food_group.name
            td = food_group.description
            td
              = link_to food_group_path(food_group), class: 'btn btn-link', data: { toggle: :tooltip, placement: :top}, title: t('actions.show', name: '') do
                i.icon-eye
              = link_to edit_food_group_path(food_group), class: 'btn btn-link', data: { toggle: :tooltip, placement: :top}, title: t('actions.edit', name: '') do
                i.icon-note
              =< link_to food_group, data: { confirm: t('alerts.are_you_sure'), toggle: :tooltip, placement: :top }, method: :delete, class: 'btn btn-link', title: t('actions.destroy', name: '') do
                i.icon-close.text-danger
    .d-flex.float-right
      .mr-3.pt-2
        = page_entries_info @food_groups
      => paginate @food_groups
      - unless @food_groups.empty?
        = link_to food_groups_path(format: :csv, params: request.query_parameters), class: 'btn btn-primary rounded h-35px ml-2' do
          i.icon-cloud-download

app/views/food_groups/show.html.slim
.row.justify-content-md-center
  .col-7
    ul.list-group.rounded-top
      li.list-group-item.rounded-top.active
        h4.pull-left.m-0
          = FoodGroup.model_name.human
          small  ##{ @food_group.id }
        = link_to edit_food_group_path(@food_group), class: 'text-white pull-right', data: { toggle: :tooltip, placement: :top}, title: t('actions.edit', name: '') do
          i.icon-note
      li.list-group-item
        h6.w-100px.d-inline-flex.font-weight-bold.text-uppercase.text-monospace
          span.float-right
            = FoodGroup.human_attribute_name :name
        span.float-right
          = @food_group.name
      li.list-group-item.rounded-bottom
        h6.w-100px.d-inline-flex.font-weight-bold.text-uppercase.text-right.text-monospace
          = FoodGroup.human_attribute_name :description
        span.float-right
          = @food_group.description || '--'

    = link_to t('actions.back'), food_groups_path, class: 'btn btn-secondary rounded mt-3 float-right'