config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :foods
  resources :food_groups
  resources :components
  resources :traits
  devise_for :users
  root 'home#index'
end

app/models/food.rb
# frozen_string_literal: true

class Food < ApplicationRecord
  include Blamable

  belongs_to :food_group

  validates :name, presence: true, length: { in: 5..100 }, uniqueness: { case_sensitive: false }
  validates :description, length: { maximum: 500 }

  delegate :name, to: :food_group, prefix: true
end

app/controllers/foods_controller.rb
# frozen_string_literal: true

class FoodsController < ApplicationController
  before_action :set_food, only: %i[create show edit update destroy]
  before_action :set_breadcrumbs

  def index
    @q = Food.ransack(params[:q])
    @foods = @q.result(distinct: true).includes(:food_group, :created_by, :updated_by).order(created_at: :desc)

    respond_with(@foods) do |format|
      format.html { @foods = @foods.page(@page).per(@per_page) }
      format.csv do
        render body: FoodGroup.to_csv(@foods, %i[food_group_name name description created_by_email created_at])
      end
    end
  end

  def show
    respond_with @food
  end

  def new
    @food = Food.new
    respond_with @food
  end

  def edit; end

  def create
    @food.save
    respond_with @food
  end

  def update
    @food.update food_params
    respond_with @food
  end

  def destroy
    @food.destroy
    respond_with @food
  end

  private

  def set_breadcrumbs
    set_breadcrumbs_for(Food, @food)
  end

  def set_food
    @food = params.key?(:id) ? Food.find(params[:id]) : Food.new(food_params)
  end

  def food_params
    params.require(:food).permit(:food_group_id, :name, :description)
  end
end

app/views/foods/_filter.html.slim
#search
  .card.rounded
    #headingOne.card-header.rounded-top[role="tab"]
      a.collapsed[data-toggle="collapse" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne"]
        i.icons.icon-magnifier
        =< t('actions.filter')
      .card-header-actions
        a.card-header-action.btn-minimize[href="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true"]
          i.icon-arrow-up
    #collapseOne.collapse[role="tabpanel" aria-labelledby="headingOne" data-parent="#search" style=""]
      = search_form_for @q do |f|
        .card-body
          .row
            .form-group.col-sm-3
              = f.label :name_cont
              = f.search_field :name_cont, class: 'form-control'
            .form-group.col-sm-3
              = f.label :description_cont
              = f.search_field :description_cont, class: 'form-control'
        .card-footer.rounded-bottom.text-right
          = f.submit t('actions.filter'), class: 'btn btn-primary rounded'

app/views/foods/_form.html.slim
.row.justify-content-md-center
  .card.rounded.w-75
    .card-header.rounded-top
      i.icon-note
      =< t("actions.#{@food.persisted? ? 'edit' : 'new'}", name: Food.model_name.human)

    = simple_form_for @food do |f|
      .card-body
        = f.error_notification
        = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

        .form-inputs
          = f.association :food_group
          = f.input :name
          = f.input :description

      .card-footer.rounded-bottom.text-right
        =< link_to t('actions.back'), foods_path, class: 'btn btn-secondary rounded'
        = f.button :submit, class: 'btn btn-primary rounded ml-2' do
          i.fa.fa-pencil.fa-lg

app/views/foods/edit.html.slim
== render 'form'

app/views/foods/index.html.slim
== render 'filter'

.card.rounded.card-accent-primary
  .card-header.rounded-top
    i.icons.icon-list
    =< Food.model_name.human.pluralize
    .card-header-actions
      = link_to new_food_path, class: 'card-header-action' do
        i.icon-note
  .card-body
    table.table.table-responsive-sm.table-striped
      thead
        tr
          th = Food.human_attribute_name :food_group
          th = Food.human_attribute_name :name
          th = Food.human_attribute_name :created_at
          th = Food.human_attribute_name :created_by
          th.w-150px
      tbody
        - @foods.each do |food|
          tr
            td = food.food_group_name
            td = food.name
            td = food.created_at.to_formatted_s :short
            td = food.created_by.email
            td
              = link_to food_path(food), class: 'btn btn-link', data: { toggle: :tooltip, placement: :top}, title: t('actions.show', name: '') do
                i.icon-eye
              = link_to edit_food_path(food), class: 'btn btn-link', data: { toggle: :tooltip, placement: :top}, title: t('actions.edit', name: '') do
                i.icon-note
              =< link_to food, data: { confirm: t('alerts.are_you_sure'), toggle: :tooltip, placement: :top }, method: :delete, class: 'btn btn-link', title: t('actions.destroy', name: '') do
                i.icon-close.text-danger
    .d-flex.float-right
      .mr-3.pt-2
        = page_entries_info @foods
      => paginate @foods
      - unless @foods.empty?
        = link_to foods_path(format: :csv, params: request.query_parameters), class: 'btn btn-primary rounded h-35px ml-2' do
          i.icon-cloud-download

app/views/foods/new.html.slim
== render 'form'

app/views/foods/show.html.slim
.row.justify-content-md-center
  .col-7
    ul.list-group.rounded-top
      li.list-group-item.rounded-top.active
        h4.pull-left.m-0
          = Food.model_name.human
          small  ##{ @food.id }
        = link_to edit_food_path(@food), class: 'text-white pull-right', data: { toggle: :tooltip, placement: :top}, title: t('actions.edit', name: '') do
          i.icon-note
      li.list-group-item
        h6.w-100px.d-inline-flex.font-weight-bold.text-uppercase.text-monospace
          span.float-right
            = Food.human_attribute_name :food_group
        span.float-right
          = @food.food_group_name
      li.list-group-item
        h6.w-100px.d-inline-flex.font-weight-bold.text-uppercase.text-monospace
          span.float-right
            = Food.human_attribute_name :name
        span.float-right
          = @food.name
      li.list-group-item.rounded-bottom
        h6.w-100px.d-inline-flex.font-weight-bold.text-uppercase.text-right.text-monospace
          = Food.human_attribute_name :description
        span.float-right
          = @food.description || '--'

    = link_to t('actions.back'), food_groups_path, class: 'btn btn-secondary rounded mt-3 float-right'